### ISSUE TITLE
Problem with dataset

### ISSUE THREAD

**Issue by TsinghuaPhantom** [seuqaj114/paig#4]
Hi, nice work, i have checked you dataset in Google drive and got confused. For example the data Datasets/3bp_color/color_3bp_vx2_vy2_sl40_r2_g60_m1_dt05.npz. 
The size of train_x is <class 'tuple'>: (10, 40, 36, 36, 3) which means the training set contains only 10 samples. Shouldn't is have more like 5000?

**Comment by janacht** [comment]
I'm having the same problem, what was your solution?

**Comment by TsinghuaPhantom** [comment]
> I'm having the same problem, what was your solution?

Just generate the dataset by yourself using the code in https://github.com/seuqaj114/paig/blob/master/nn/datasets/generators.py.
